Create user entity
joeliths/FireWolf pull request #34
Opened 2019-11-22 10:46 UTC by IdaFagerlund

2019-11-22 12:47 UTC, DaniellaNoren requested changes
what the fuuuck

2019-11-22 12:47 UTC, DaniellaNoren commented on src/main/java/com/example/demo/entities/User.java
> +public class User {
Why the fuck did you do this!?????+1?!?!?!??!?!?!?

2019-11-22 12:47 UTC, DaniellaNoren commented on src/main/java/com/example/demo/entities/User.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Oh no!!!

2019-11-22 12:57 UTC, IdaFagerlund commented on src/main/java/com/example/demo/entities/User.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
fixed!

2019-11-25 10:23 UTC, joeliths approved these changes

2019-11-25 10:25 UTC, PontusF approved these changes

2019-11-25 10:25 UTC, joeliths approved these changes

2019-11-25 10:27 UTC, merged